name: Restrict Push Access

on:
  push:
    branches:
      - '*'

jobs:
  check-branch-owner:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is branch owner
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          OWNER="${GITHUB_ACTOR}"

          # Assuming branch names are in the format 'username/branch-name'
          if [[ "$BRANCH_NAME" != "$OWNER/"* ]]; then
            echo "You do not have permission to push to this branch."
            exit 1
          fi
