name: Restrict Push Access

on:
  push:
    branches:
      - '*'

jobs:
  check-branch-owner:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is branch owner
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ "$BRANCH_NAME" != "${GITHUB_ACTOR}" ]]; then
            echo "You do not have permission to push to this branch."
            exit 1
          fi
